### ISSUE TITLE
mathjex 插入公式后渲染问题

### ISSUE THREAD

**Issue by wmpscc** [dongyuanxin/theme-bmw#13]
你好，在markdown文件中插入数学公式后，执行`hexo g`命令会报错
```
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 2, Column 30]
  parseAggregate: expected colon after dict key
    at Object._prettifyError (/home/heolis/文档/blog/ishero.net/ishero/node_modules/nunjucks/src/lib.js:36:11)
    at Template.render (/home/heolis/文档/blog/ishero.net/ishero/node_modules/nunjucks/src/environment.js:526:21)
    at Environment.renderString (/home/heolis/文档/blog/ishero.net/ishero/node_modules/nunjucks/src/environment.js:364:17)
    at Promise.fromCallback.cb (/home/heolis/文档/blog/ishero.net/ishero/node_modules/hexo/lib/extend/tag.js:62:48)
    at tryCatcher (/home/heolis/文档/blog/ishero.net/ishero/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (/home/heolis/文档/blog/ishero.net/ishero/node_modules/bluebird/js/release/promise.js:180:30)
    at Tag.render (/home/heolis/文档/blog/ishero.net/ishero/node_modules/hexo/lib/extend/tag.js:62:18)
    at Object.onRenderEnd (/home/heolis/文档/blog/ishero.net/ishero/node_modules/hexo/lib/hexo/post.js:282:20)
    at Promise.then.then.result (/home/heolis/文档/blog/ishero.net/ishero/node_modules/hexo/lib/hexo/render.js:65:19)
    at tryCatcher (/home/heolis/文档/blog/ishero.net/ishero/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/heolis/文档/blog/ishero.net/ishero/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/heolis/文档/blog/ishero.net/ishero/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/heolis/文档/blog/ishero.net/ishero/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/heolis/文档/blog/ishero.net/ishero/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/heolis/文档/blog/ishero.net/ishero/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/heolis/文档/blog/ishero.net/ishero/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/heolis/文档/blog/ishero.net/ishero/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/heolis/文档/blog/ishero.net/ishero/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```
请问这个有什么好的解决方法吗？

插入公式如下：
```
$$y = \frac{1}{{1 + {e^{ - z}}}}$$
```

**Comment by dongyuanxin** [comment]
换行公式：
```
$$
y = \frac{1}{{1 + {e^{ - z}}}}
$$
```

行内公式：`$ y = \frac{1}{{1 + {e^{ - z}}}} $`

**Comment by wmpscc** [comment]
我按照这个方法解决了：[解决hexo(jekyll) mathjex 插入公式后渲染问题](http://mlnote.com/2016/09/03/solved-mathjex-problem/)
